### ISSUE TITLE
CI: setup npm auto publish

### ISSUE THREAD

**Issue by rndquu** [ubiquity/rpc-handler#2]
Depends on https://github.com/ubiquity/web3-rpc-racer/pull/1

When https://github.com/ubiquity/web3-rpc-racer/pull/1 is merged we should:
1. Publish this `npm` package under the `@ubiquitydao` org
2. Setup auto publish when new changes are merged into the `main` branch (use `NPM_ACCESS_TOKEN` github organization secret)

**Comment by gentlementlegen** [comment]
@rndquu for the auto publish, it was done before in the repo https://github.com/ubiquibot/configuration/blob/development/.github/workflows/publish-package.yml
However to publish under @ubiquity we might run into some trouble as @pavlovcik didn't get the credentials back, is it still the case?

**Comment by rndquu** [comment]
> we might run into some trouble as @pavlovcik didn't get the credentials back

I don't understand, credentials for what?

**Comment by gentlementlegen** [comment]
To publish a package under an organization (any package prefixed with `@`) you need to authenticate to NPM to be able to publish there. There is already an organization existing, but I don't know who owns it: https://www.npmjs.com/org/ubiquity

**Comment by rndquu** [comment]
> To publish a package under an organization (any package prefixed with `@`) you need to authenticate to NPM to be able to publish there. There is already an organization existing, but I don't know who owns it: https://www.npmjs.com/org/ubiquity

@pavlovcik Did you create this one https://www.npmjs.com/org/ubiquity? Pls invite @FernandVEYRIER  and rndquu@gmail.com

**Comment by 0x4007** [comment]
I can't find how to invite but I dm access tokens. Let's use `@ubiquitydao` assuming you have the option to choose to which organization.

**Comment by rndquu** [comment]
I've added npm access token to github organization secrets (`NPM_ACCESS_TOKEN `)
