### ISSUE TITLE
Published without types

### ISSUE THREAD

**Issue by Keyrxng** [ubiquity/rpc-handler#21]
I'm unsure what's caused this but it's been published without types.

- https://www.npmjs.com/package/@ubiquity-dao/rpc-handler?activeTab=code 

- https://www.npmjs.com/package/@keyrxng/rpc-handler?activeTab=code what it should look like

running `yarn build` then `yarn pack` followed by `tar -tf ubiquity-dao-rpc-handler-v1.1.0.tgz` locally reveals:

```bash
...
package/dist/types
package/dist/cjs/index.js
package/dist/esm/index.js
package/dist/types/constants.d.ts
package/dist/types/handler.d.ts
package/dist/types/rpc-handler.d.ts
```

Looking at the [run](https://github.com/ubiquity/rpc-handler/actions/runs/9180797875/job/25246055017) reveals:

```bash
npm notice 📦  @ubiquity-dao/rpc-handler@1.1.0
npm notice === Tarball Contents === 
npm notice 2.5kB   README.md        
npm notice 1.5MB   dist/cjs/index.js
npm notice 572.7kB dist/esm/index.js
npm notice 573.1kB dist/index.js    
npm notice 2.6kB   package.json     
npm notice === Tarball Details === 
```

Looking at both versions of the UBQ package neither has `/types` or any `d.ts` files. While all four of my versions have either `/types` or `.d.ts` files.

<hr/>

The only difference between the two workflows is `publish` is broken off into an additional step (don't see why that would affect it).

Locally the types are built as expected.

**Comment by Keyrxng** [comment]
@Sadaf-A just a heads up, #24 is likely to resolve this issue already.

The error has been potentially identified as being either:

1. How the yarn scripts are executing in the context of the wf.
2. The arrangement/execution flow of the wf itself.

> updated the yarn build command which I hope will fix the issue where the NPM push actually has the types included. I thought perhaps the postbuild was not executing in the wf? We'll see after this is bumped.

<hr/>

Just giving you more context to work with, do with it what you will

**Comment by 0x4007** [comment]
@gentlementlegen I think a good starting point is to try and match the settings on v2 so we can ensure that everything is working as expected. I'm not sure if there is a bug that it can't read pull comments or if those rewards are disabled.

**Comment by gentlementlegen** [comment]
@0x4007 It'd be nice to have the metadata to help investigating bugs. Will look into it.
