### ISSUE TITLE
Proxify returned provider

### ISSUE THREAD

**Issue by Keyrxng** [ubiquity/rpc-handler#23]
Rather than returning a list of RPCs considered valid based on their `eth_getBlockNumber` response and the burden being on the package user to handle call failures > endpoint reselection via the module, it should be built-in directly.

To do this, the package should return a JS `Proxy` to the provider. This `Proxy` should effectively handle call retries, RPC reselection, error feedback and be configurable.

This means that any read/write op a user makes will now pass through the module (as opposed to only read ops in the linked issue) which is a lot of ground to cover in terms of potential errors.

A proxy user should never need to get involved with errors unless they have caused them more or less and since what they assign as their `"app.provider"` is our `Proxy` they should never need to change provider.

<hr/>

- The proxy should be the default
- Expose both the proxy and a non-proxied version (basically what the package does now)
- configurables: breakpoints, tiered log output, log message constants
- tests should cover read & write ops, as well as any new functionality

<hr/>

The intention is that for a package user everything out of their control is abstracted away, they ask for a provider and it just works unless ofc it's user error.

The expectation is that the user would receive valuable error feedback only if the package is not able to complete the op and this really should only ever happen because of user error.

User-side [Proxy implementation](https://github.com/ubq-testing/pay.ubq.fi/blob/development/static/scripts/rewards/web3/onchain-call-handler.ts) for reference

_original context https://github.com/ubiquity/pay.ubq.fi/issues/235_

##### time: hard to say, <1 day maybe more

**Comment by Keyrxng** [comment]
Those rewards are crazy, I feel like the bot fcking loves me/takes sympathy 😂 It's almost like I've somehow ended up with your shares (obv not)

**Comment by 0x4007** [comment]
> Those rewards are crazy, I feel like the bot fcking loves me/takes sympathy 😂 It's almost like I've somehow ended up with your shares (obv not)

The relevance scoring is broken but it seems like your average is roughly at 60%. You may notice a difference once its fixed in v2.

**Comment by 0x4007** [comment]
> ### [ [ 625.935 WXDAI ] ](undefined)
> ###### @Keyrxng

@gentlementlegen any idea why it has no rewards for everybody else?

**Comment by gentlementlegen** [comment]
@0x4007 not sure no. Linked that PR to an issue, will have a look at it.
