### ISSUE TITLE
Make fastest network finding more efficient

### ISSUE THREAD

**Issue by gentlementlegen** [ubiquity/rpc-handler#43]
Instead of trying to resolve all the promises to see which network is the fastest, it would be more efficient to return the first one that resolves the network call successfully as it is probably the fastest.

              @Keyrxng @0x4007 I changed the logic a bit so instead of naively removing the first RPC of the list, the failing RPC is actually removed.

This also made me wonder, why do we test every endpoint when we are only interested in the fastest one, aka the first one to successfully fulfill the response? If we have to wait for slow RPCs, for example one that take 5 seconds to complete, doesn't it defeat the purpose of the function?

_Originally posted by @gentlementlegen in https://github.com/ubiquity/rpc-handler/issues/33#issuecomment-2255230177_

**Comment by 0x4007** [comment]
@gentlementlegen I added the labels for you 😄

**Comment by gentlementlegen** [comment]
@0x4007 It seems that closing issues automatically does not trigger the conversation rewards. Maybe this is because the actor is a bot so it gets skipped by the kernel.
