### ISSUE TITLE
Support `Ethers` versions 5 and 6

### ISSUE THREAD

**Issue by Keyrxng** [ubiquity/rpc-handler#49]
### Why this change?

In order to facilitate a smoother migration from `ethers@v5` to `ethers@v6` this package should be able to return either version depending on the init value passed in via the config.

### What should be done?

- Install both versions of the ethers package
- Add a new optional config item which defaults to `ethers@v5` 
- Depending on the value passed in return the appropriate provider
- add tests to verify that the provider returned is actually the intended version

_original [context](https://github.com/ubiquibot/crypto-faucet-plugin/pull/1#discussion_r1736220566)_

**Comment by 0x4007** [comment]
Just use 5. ChatGPT supports 5 and not 6. What feature does 6 have that makes it worth the trouble to upgrade?

**Comment by Keyrxng** [comment]
> Web3Provider (which historically was used to wrap [link-web3](https://github.com/ethereum/web3.js) providers) is now called [BrowserProvider](https://docs.ethers.org/v6/api/providers/#BrowserProvider) which is designed to wrap EIP-1193 providers, which is the standard that both modern Web3.js and injected providers offer.

Is probably the biggest reason for it but more can be found [here](https://docs.ethers.org/v6/migrating/)

**Comment by 0x4007** [comment]
Is this a relevant problem to our current infra? Why bother upgrading if 5 works for our needs?

**Comment by Keyrxng** [comment]
1. Modern packages that we are going to be relying on soon want `ethers@v6` these being Gnosis SDK and various AA providers as one example. If we do not offer a `v6` version we'll need to lose the Proxy benefits and create a new `v6` provider using the rpc which `rpc-handler` returns.
2. Unless we are the only intended users of `rpc-handler` I'd imagine users would want `v6` too.
3. In regards to our current infrastructure, we could get away with using just `v5` if we had to.

> what is EIP-1193? What are the benefits of supporting it in your dapp?
https://chatgpt.com/share/8bb6a263-0988-4174-bb38-fa7938bfdc94

**Comment by 0x4007** [comment]
Let's invest the time and money for this upgrade if there is a tangible blocker at present.
